ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    exclude: ^.idea/
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=16384
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending

  # Mypy runs without local dependencies, so we disable some strict-mode flags
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy
        exclude: tests
        args:
          - --allow-subclassing-any
          - --no-warn-return-any
          - --ignore-missing-imports
          - --allow-untyped-decorators
        additional_dependencies: [tokenize-rt==3.2.0, pydantic==1.10.13]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.284
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python supported by your project here
        language_version: python3.10
